# -*- coding: utf-8 -*-
"""Regression_Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3C83K-XS9T45FZCE2BuZtbC2vBBtY91

dataset: https://drive.google.com/file/d/1_WGEMLNc29LnqzJOb6cGrFiENxWzQYIt/view?usp=sharing
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import statsmodels.api as sm

# Load your data from the CSV file
data = pd.read_csv('/content/gdrive/MyDrive/SIB Greatedu praktik/regg/insurance_training.csv')
data.set_index("id", inplace=True)
data

# Assuming you have a target variable (y) and predictor variables (X)
# Adjust the column names accordingly
X = data.drop('charges', axis=1)
X = sm.add_constant(X)  # Add a constant term (intercept)
y = data['charges']

# Fit the linear regression model using statsmodels
model = sm.OLS(y, X).fit()

# Get a summary of the regression model
model_summary = model.summary()

# Print the model summary
print(model_summary)

"""P-value < Alpha ==> Signifikan"""